failfast:
  authorized_groups: [COLLABORATOR, MEMBER, OWNER]
  authorized_users: []
  build:
    on-branches: [master, main, production]
    on-comments: [/retest, /test]
    on-labels: [ok-to-test]
    on-pullrequests: ['*']
  debug: false
  env: development
  # Ingress url to the failfast api
  failfast_url: https://failfast-ci.com
  enable_linter: false

github:
  context: failfast-ci
  integration_id: 100000
  secret_token: '' # "GITHUB_HOOK_SECRET"

gitlab:
  enable_container_registry: false
  enable_issues: false
  enable_jobs: true
  enable_merge_requests: false
  enable_shared_runners: false
  enable_snippets: false
  enable_wiki: false
  gitlab_url: https://gitlab.com

  # Default group on gitlab
  namespace: failfast-ci
  webhook_url: "https://failfast-ci.com/api/v1/gitlab_event"
  privacy: private
  repo: null
  # Gitlab robot user to add as owner
  robot-user: antoine.legrand
  runner_tags:
    - failfast-ci
  secret_token: $GITLAB_ACCESS_TOKEN
  timeout: 30
